/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.organization.ngoAdminWorkArea;

import business.organization.NGOOrganization;
import business.organization.Organization;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class NGOWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOJPanel
     */
    private JPanel userProcessContainer;
    private Organization organization;
    private NGOOrganization nGOOrganization;
    private UserAccount userAccount;

    public NGOWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, NGOOrganization nGOOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.nGOOrganization = nGOOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderGrocery = new javax.swing.JButton();
        orderFood = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        orderGrocery.setText("Grocery Work Request");
        orderGrocery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderGroceryActionPerformed(evt);
            }
        });

        orderFood.setText("Restaurant Food Request");
        orderFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderFoodActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NGO Admin Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(orderFood, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderGrocery, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(orderGrocery)
                .addGap(47, 47, 47)
                .addComponent(orderFood)
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderGroceryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderGroceryActionPerformed
        NGOManageGroceryRequestJPanel ngoManageGroceryRequestJPanel = new NGOManageGroceryRequestJPanel(userProcessContainer, userAccount, nGOOrganization);
        userProcessContainer.add("ngoManageGroceryRequestJPanel", ngoManageGroceryRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderGroceryActionPerformed

    private void orderFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderFoodActionPerformed
        NGOManageRestaurantFoodRequestJPanel ngoManageRestaurantFoodRequestJPanel = new NGOManageRestaurantFoodRequestJPanel(userProcessContainer, userAccount, nGOOrganization);
        userProcessContainer.add("ngoManageRestaurantFoodRequestJPanel", ngoManageRestaurantFoodRequestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderFoodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderFood;
    private javax.swing.JButton orderGrocery;
    // End of variables declaration//GEN-END:variables
}
