/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.organization.groceryManagerWorkArea;

import business.enterprise.Enterprise;
import business.organization.GroceryOrganization;
import business.organization.HouseholdOrganization;
import business.organization.Organization;
import business.organization.RestaurantOrganization;
import business.product.Product;
import business.userAccount.UserAccount;
import business.workQueue.StatusEnum;
import business.workQueue.UglyGroceryWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class GroceryManagerPlaceRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GroceryManagePlaceRequestJPanel
     */
    private JPanel userProcessContainer;
    private GroceryOrganization groceryOrganization;
    private UserAccount userAccount;
    private Enterprise enterprise;

    public GroceryManagerPlaceRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, GroceryOrganization groceryOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.groceryOrganization = groceryOrganization;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        populateProductJComboBox();
        populateRequestJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        placeRequestjButton = new javax.swing.JButton();
        productjComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        quantityjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pricejTextField = new javax.swing.JTextField();

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Publish Grocery Request");

        requestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price", "Total Quantity", "Available Quantity", "Raised by", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requestJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(requestJTable);
        if (requestJTable.getColumnModel().getColumnCount() > 0) {
            requestJTable.getColumnModel().getColumn(3).setResizable(false);
            requestJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setText("Product Name:");

        placeRequestjButton.setText("Publish Request");
        placeRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeRequestjButtonActionPerformed(evt);
            }
        });

        productjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Quantity:");

        jLabel4.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(placeRequestjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(productjComboBox, 0, 310, Short.MAX_VALUE)
                                    .addComponent(quantityjTextField)
                                    .addComponent(pricejTextField))))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(productjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(placeRequestjButton)
                .addGap(108, 108, 108))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void placeRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeRequestjButtonActionPerformed
        int totalQuantity = 0;
        float amount = 0;

        Product product = (Product) productjComboBox.getSelectedItem();
        try {
            totalQuantity = Integer.parseInt(quantityjTextField.getText());
            amount = Float.parseFloat(pricejTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please provide numeric values", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        UglyGroceryWorkRequest uglyGroceryWorkRequest = new UglyGroceryWorkRequest();
        uglyGroceryWorkRequest.setProduct(product);
        uglyGroceryWorkRequest.setTotalQuantity(totalQuantity);
        uglyGroceryWorkRequest.setAmount(amount);
        uglyGroceryWorkRequest.setSender(userAccount);
        uglyGroceryWorkRequest.setOrganizationName(groceryOrganization.getOrganizationName());
        uglyGroceryWorkRequest.setStatus(StatusEnum.GroceryToSell);
        Organization org = null;
        boolean isFound = false;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof RestaurantOrganization) {
                org = organization;
                isFound = true;
                break;
            }
        }
        if (org != null) {
            org.getUglyGroceryWorkQueue().getUglyGroceryWorkRequestList().add(uglyGroceryWorkRequest);
        }

        org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof HouseholdOrganization) {
                org = organization;
                isFound = true;
                break;
            }
        }

        if (org != null) {
            org.getUglyGroceryWorkQueue().getUglyGroceryWorkRequestList().add(uglyGroceryWorkRequest);
        }

        if (isFound) {
            userAccount.getGroceryWorkQueue().getUglyGroceryWorkRequestList().add(uglyGroceryWorkRequest);
        }

        populateRequestJTable();
        quantityjTextField.setText("");
        pricejTextField.setText("");
        productjComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_placeRequestjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton placeRequestjButton;
    private javax.swing.JTextField pricejTextField;
    private javax.swing.JComboBox productjComboBox;
    private javax.swing.JTextField quantityjTextField;
    private javax.swing.JTable requestJTable;
    // End of variables declaration//GEN-END:variables

    private void populateProductJComboBox() {
        productjComboBox.removeAllItems();
        for (Product product : groceryOrganization.getProductCatalog().getProductCatalog()) {
            productjComboBox.addItem(product);
        }
    }

    private void populateRequestJTable() {
        DefaultTableModel model = (DefaultTableModel) requestJTable.getModel();

        model.setRowCount(0);

        for (UserAccount ua : groceryOrganization.getUserAccountDirectory().getUserAccountList()) {
            for (UglyGroceryWorkRequest workRequest : ua.getGroceryWorkQueue().getUglyGroceryWorkRequestList()) {
                workRequest.checkExpired();
                Object[] row = new Object[6];
                row[0] = workRequest.getProduct();
                row[1] = workRequest.getAmount();
                row[2] = workRequest.getTotalQuantity();
                row[3] = workRequest.getAvailQuantity();
                row[4] = workRequest.getSender();
                row[5] = workRequest.getStatus();
                model.addRow(row);
            }
        }
    }
}
