/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.organization.restaurantManagerWorkArea;

import business.enterprise.EndPointEnterprise;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.NGOOrganization;
import business.organization.Organization;
import business.organization.RestaurantOrganization;
import business.userAccount.UserAccount;
import business.workQueue.FoodOfferWorkRequest;
import business.workQueue.StatusEnum;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dhanashree Chavan
 */
public class RestaurantManagerDonateRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GroceryManagerDonateRequestJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Network network;
    private RestaurantOrganization restaurantOrganization;

    public RestaurantManagerDonateRequestJPanel(JPanel userProcessContainer, UserAccount userAccount, Network network, RestaurantOrganization restaurantOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.network = network;
        this.restaurantOrganization = restaurantOrganization;
        populateNGOJComboBox();
        populateFoodOfferWorkRequestJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodOfferWorkRequestJTable = new javax.swing.JTable();
        donatejButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ngoJComboBox = new javax.swing.JComboBox();

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Donate Food Request");

        foodOfferWorkRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu Item", "Total Quantity", "Available Quantity", "Raised by", "Restaurant Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(foodOfferWorkRequestJTable);

        donatejButton.setText("Donate");
        donatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donatejButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("NGO Name:");

        ngoJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(ngoJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(donatejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ngoJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(donatejButton))
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void donatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donatejButtonActionPerformed
        int selectedRow = foodOfferWorkRequestJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }

        FoodOfferWorkRequest selectedRequest = (FoodOfferWorkRequest) foodOfferWorkRequestJTable.getValueAt(selectedRow, 4);
        Organization selectedNGO = (NGOOrganization) ngoJComboBox.getSelectedItem();
        selectedNGO.getFoodOfferWorkQueue().getFoodOfferWorkRequestList().add(selectedRequest);
        selectedRequest.setStatus(StatusEnum.RestaurantToDonate);
        JOptionPane.showMessageDialog(null, "Request sent to " + selectedNGO + ". Thank You!!");
        populateFoodOfferWorkRequestJTable();
    }//GEN-LAST:event_donatejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton donatejButton;
    private javax.swing.JTable foodOfferWorkRequestJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox ngoJComboBox;
    // End of variables declaration//GEN-END:variables

    private void populateNGOJComboBox() {
        ngoJComboBox.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (enterprise instanceof EndPointEnterprise) {
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof NGOOrganization) {
                        ngoJComboBox.addItem(organization);
                    }

                }
                break;
            }
        }
    }

    private void populateFoodOfferWorkRequestJTable() {
        DefaultTableModel model = (DefaultTableModel) foodOfferWorkRequestJTable.getModel();

        model.setRowCount(0);

        for (UserAccount ua : restaurantOrganization.getUserAccountDirectory().getUserAccountList()) {
            for (FoodOfferWorkRequest workRequest : ua.getFoodOfferWorkQueue().getFoodOfferWorkRequestList()) {
                workRequest.checkExpired();
                if (workRequest.getStatus().equals(StatusEnum.RestaurantToSell)) {
                    Object[] row = new Object[5];
                    row[0] = workRequest.getProduct();
                    row[1] = workRequest.getTotalQuantity();
                    row[2] = workRequest.getAvailQuantity();
                    row[3] = workRequest.getSender();
                    row[4] = workRequest;
                    model.addRow(row);
                }
            }
        }
    }

}
