/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.organization.householdWorkArea;

import business.enterprise.Enterprise;
import business.organization.HouseholdOrganization;
import business.organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Monas
 */
public class HouseholdWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private HouseholdOrganization householdOrganization;

    public HouseholdWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,HouseholdOrganization householdOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.householdOrganization=householdOrganization;
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        orderGrocery = new javax.swing.JButton();
        orderFood = new javax.swing.JButton();
        viewPreviousGroceryOrderBtn = new javax.swing.JButton();
        viewPreviousFoodOfferBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(881, 591));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Household Admin Work Area");

        orderGrocery.setText("Order Grocery");
        orderGrocery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderGroceryActionPerformed(evt);
            }
        });

        orderFood.setText("Order Food");
        orderFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderFoodActionPerformed(evt);
            }
        });

        viewPreviousGroceryOrderBtn.setText("View Previous Grocery Orders");
        viewPreviousGroceryOrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPreviousGroceryOrderBtnActionPerformed(evt);
            }
        });

        viewPreviousFoodOfferBtn.setText("View Previous Food Orders");
        viewPreviousFoodOfferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPreviousFoodOfferBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(184, 184, 184))
            .addGroup(layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orderFood, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderGrocery, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPreviousGroceryOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPreviousFoodOfferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(orderGrocery)
                .addGap(47, 47, 47)
                .addComponent(orderFood)
                .addGap(45, 45, 45)
                .addComponent(viewPreviousGroceryOrderBtn)
                .addGap(43, 43, 43)
                .addComponent(viewPreviousFoodOfferBtn)
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderGroceryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderGroceryActionPerformed
        HouseholdOrderGroceryJPanel householdOrderGroceryJPanel = new HouseholdOrderGroceryJPanel(userProcessContainer,householdOrganization,enterprise);
        userProcessContainer.add("householdOrderGroceryJPanel", householdOrderGroceryJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderGroceryActionPerformed

    private void orderFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderFoodActionPerformed
        HouseholdOrderFoodJPanel householdOrderFoodJPanel = new HouseholdOrderFoodJPanel(userProcessContainer,householdOrganization,enterprise);
        userProcessContainer.add("householdOrderFoodJPanel", householdOrderFoodJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderFoodActionPerformed

    private void viewPreviousGroceryOrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPreviousGroceryOrderBtnActionPerformed
        HouseholdViewPreviousGroceryOrdersJPanel householdViewPreviousOrdersJPanel = new HouseholdViewPreviousGroceryOrdersJPanel(userProcessContainer, householdOrganization);
        userProcessContainer.add("householdViewPreviousOrdersJPanel", householdViewPreviousOrdersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPreviousGroceryOrderBtnActionPerformed

    private void viewPreviousFoodOfferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPreviousFoodOfferBtnActionPerformed
        HousholdViewPreviousFoodOrdersJPanel housholdViewPreviousFoodOrdersJPanel = new HousholdViewPreviousFoodOrdersJPanel(userProcessContainer, householdOrganization);
        userProcessContainer.add("housholdViewPreviousFoodOrdersJPanel", housholdViewPreviousFoodOrdersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPreviousFoodOfferBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orderFood;
    private javax.swing.JButton orderGrocery;
    private javax.swing.JButton viewPreviousFoodOfferBtn;
    private javax.swing.JButton viewPreviousGroceryOrderBtn;
    // End of variables declaration//GEN-END:variables

    
}
