/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.organization.householdWorkArea;

import business.enterprise.Enterprise;
import business.order.foodOffer.FoodOfferOrder;
import business.order.foodOffer.FoodOfferOrderItem;
import business.organization.HouseholdOrganization;
import business.organization.Organization;
import business.workQueue.FoodOfferWorkRequest;
import business.workQueue.StatusEnum;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class HouseholdOrderFoodJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HouseholdOrderFoodJPanel
     */
    private JPanel userProcessContainer;
    private HouseholdOrganization householdOrganization;
    private FoodOfferOrder foodOfferOrder;
    private Enterprise enterprise;
    private boolean isCheckedOut = false;

    public HouseholdOrderFoodJPanel(JPanel userProcessContainer, HouseholdOrganization householdOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.householdOrganization = householdOrganization;
        this.enterprise = enterprise;
        if (!isCheckedOut) {
            foodOfferOrder = new FoodOfferOrder();
        }

        populateFoodOfferTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodOfferTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        quantityjSpinner = new javax.swing.JSpinner();
        addBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        cartJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        checkOutBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Food");

        foodOfferTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Price", "Restaurant"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(foodOfferTable);
        if (foodOfferTable.getColumnModel().getColumnCount() > 0) {
            foodOfferTable.getColumnModel().getColumn(0).setResizable(false);
            foodOfferTable.getColumnModel().getColumn(1).setResizable(false);
            foodOfferTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel3.setText("Select Quantity:");

        quantityjSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        addBtn.setText("Add to Cart");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        cartJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(cartJTable);

        jLabel2.setText("My Cart:");

        checkOutBtn.setText("Check out");
        checkOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantityjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2)
                            .addComponent(checkOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(113, 113, 113))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(jLabel3)
                    .addComponent(quantityjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(checkOutBtn)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = foodOfferTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }

        FoodOfferWorkRequest selectedProduct = (FoodOfferWorkRequest) foodOfferTable.getValueAt(selectedRow, 3);
        int fetchQty = (Integer) quantityjSpinner.getValue();
        if (fetchQty <= 0) {
            JOptionPane.showMessageDialog(null, "Quantity cannot be less than or equal to zero.");
            return;
        }

        try {
            int tempQuantity = 0;
            for (FoodOfferOrderItem oi : foodOfferOrder.getFoodOfferOrderItemList()) {
                if (oi.getFoodOfferWorkRequest() == selectedProduct) {
                    tempQuantity = oi.getQuantity();
                    break;
                }
            }
            if (fetchQty <= (selectedProduct.getAvailQuantity() - tempQuantity)) {
                boolean alreadyPresent = false;
                for (FoodOfferOrderItem oi : foodOfferOrder.getFoodOfferOrderItemList()) {
                    if (oi.getFoodOfferWorkRequest() == selectedProduct) {
                        oi.setQuantity(fetchQty + oi.getQuantity());
                        alreadyPresent = true;
                        populateFoodOfferTable();
                        refreshOrderTable();
                        break;
                    }
                }
                if (!alreadyPresent) {
                    foodOfferOrder.addFoodOfferOrderItem(selectedProduct, fetchQty);
                    populateFoodOfferTable();
                    refreshOrderTable();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Quantity > Availablity.", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Invalid Quantity.");
            return;
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void checkOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutBtnActionPerformed
        // TODO add your handling code here:
        if (foodOfferOrder.getFoodOfferOrderItemList().size() > 0) {
            householdOrganization.getFoodOfferMasterOrderCatalog().addOrder(foodOfferOrder);
            JOptionPane.showMessageDialog(null, "Order placed  successfully!");
            for (FoodOfferOrderItem oi : foodOfferOrder.getFoodOfferOrderItemList()) {
                int availQty = oi.getFoodOfferWorkRequest().getAvailQuantity() - oi.getQuantity();
                oi.getFoodOfferWorkRequest().setAvailQuantity(availQty);
                oi.getFoodOfferWorkRequest().getReceiverList().add(householdOrganization);
                if (availQty == 0) {
                    oi.getFoodOfferWorkRequest().setStatus(StatusEnum.Unavailable);
                }
            }
            foodOfferOrder = new FoodOfferOrder();
            refreshOrderTable();
            populateFoodOfferTable();
            isCheckedOut = true;
            return;
        }
        JOptionPane.showMessageDialog(null, "Your cart is empty!.", "WARNING", JOptionPane.WARNING_MESSAGE);
        return;
    }//GEN-LAST:event_checkOutBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable cartJTable;
    private javax.swing.JButton checkOutBtn;
    private javax.swing.JTable foodOfferTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner quantityjSpinner;
    // End of variables declaration//GEN-END:variables

    private void populateFoodOfferTable() {
        DefaultTableModel model = (DefaultTableModel) foodOfferTable.getModel();

        model.setRowCount(0);
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof HouseholdOrganization) {
                for (FoodOfferWorkRequest workRequest : organization.getFoodOfferWorkQueue().getFoodOfferWorkRequestList()) {
                    workRequest.checkExpired();
                    if (workRequest.getStatus().equals(StatusEnum.RestaurantToSell)) {
                        Object[] row = new Object[4];
                        row[0] = workRequest.getProduct();
                        row[1] = workRequest.getAvailQuantity();
                        row[2] = workRequest.getAmount();
                        row[3] = workRequest;
                        model.addRow(row);
                    }
                }
                break;
            }
        }
    }

    private void refreshOrderTable() {
        DefaultTableModel dtm = (DefaultTableModel) cartJTable.getModel();
        dtm.setRowCount(0);
        for (FoodOfferOrderItem oi : foodOfferOrder.getFoodOfferOrderItemList()) {
            {
                Object[] row = new Object[3];
                row[0] = oi.getFoodOfferWorkRequest().getProduct();
                row[1] = oi.getQuantity();
                row[2] = oi.getFoodOfferWorkRequest().getAmount() * oi.getQuantity();
                dtm.addRow(row);
            }
        }
    }
}
