/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.enterpriseAdminWorkArea;

import business.enterprise.Enterprise;
import business.organization.HouseholdOrganization;
import business.organization.Organization;
import business.userAccount.UserAccount;
import business.workQueue.FoodOfferWorkRequest;
import business.workQueue.StatusEnum;
import business.workQueue.UglyGroceryWorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Monas
 */
public class EnterpriseAdminViewReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminViewReport
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;

    public EnterpriseAdminViewReportJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        JFreeChart chart = createChart(createDataset());
        ChartPanel myChart = new ChartPanel(chart);
        myChart.setMouseWheelEnabled(true);

        barChartJPanel.setLayout(new java.awt.BorderLayout());
        barChartJPanel.add(myChart, BorderLayout.CENTER);
        barChartJPanel.validate();
    }

    private static JFreeChart createChart(DefaultCategoryDataset dataset) {
        JFreeChart chart = ChartFactory.createBarChart("Waste Vs Total Quantity", "Organization", "Amount", dataset, PlotOrientation.VERTICAL, true, true, false);

        return chart;
    }

    private DefaultCategoryDataset createDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (!(org instanceof HouseholdOrganization)) {
                int totalQty = 0;
                int waste = 0;
                for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                    for (UglyGroceryWorkRequest workRequest : ua.getGroceryWorkQueue().getUglyGroceryWorkRequestList()) {
                        if (workRequest.getStatus().equals(StatusEnum.Expired)) {
                            totalQty = totalQty + workRequest.getTotalQuantity();
                            waste = waste + workRequest.getAvailQuantity();
                        }
                    }
                    for (FoodOfferWorkRequest workRequest : ua.getFoodOfferWorkQueue().getFoodOfferWorkRequestList()) {
                        if (workRequest.getStatus().equals(StatusEnum.Expired)) {
                            totalQty = totalQty + workRequest.getTotalQuantity();
                            waste = waste + workRequest.getAvailQuantity();
                        }
                    }
                }
                dataset.addValue(waste, "waste", org.getOrganizationName());
                dataset.addValue(totalQty, "Total Quantity", org.getOrganizationName());
            }
        }
        return dataset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        barChartJPanel = new javax.swing.JPanel();

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Report");

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barChartJPanelLayout = new javax.swing.GroupLayout(barChartJPanel);
        barChartJPanel.setLayout(barChartJPanelLayout);
        barChartJPanelLayout.setHorizontalGroup(
            barChartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barChartJPanelLayout.setVerticalGroup(
            barChartJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addComponent(barChartJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barChartJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel barChartJPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
