/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.enterpriseAdminWorkArea;

import business.Ecosystem;
import business.enterprise.EndPointEnterprise;
import business.enterprise.Enterprise;
import business.organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Monas
 */
public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkArea
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Organization organization;
    private Ecosystem system;

    public EnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        selectedEnterpriseText.setText(enterprise.toString());
        if(enterprise instanceof EndPointEnterprise)
            viewReportBtn.setEnabled(false);
        populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        treeJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTree = new javax.swing.JTree();
        workAreaJPanel = new javax.swing.JPanel();
        manageOrganizationBtn = new javax.swing.JButton();
        manageAdminBtn = new javax.swing.JButton();
        viewReportBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectedEnterpriseText = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(881, 591));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(200);

        treeJPanel.setPreferredSize(new java.awt.Dimension(180, 552));

        enterpriseJTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                enterpriseJTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(enterpriseJTree);

        javax.swing.GroupLayout treeJPanelLayout = new javax.swing.GroupLayout(treeJPanel);
        treeJPanel.setLayout(treeJPanelLayout);
        treeJPanelLayout.setHorizontalGroup(
            treeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        treeJPanelLayout.setVerticalGroup(
            treeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(treeJPanel);

        manageOrganizationBtn.setText("Manage Organization");
        manageOrganizationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationBtnActionPerformed(evt);
            }
        });

        manageAdminBtn.setText("Manage Organization Admin");
        manageAdminBtn.setEnabled(false);
        manageAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAdminBtnActionPerformed(evt);
            }
        });

        viewReportBtn.setText("View Report");
        viewReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReportBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enterprise Admin Work Area");

        jLabel2.setText("Enterprise:");

        selectedEnterpriseText.setEnabled(false);

        javax.swing.GroupLayout workAreaJPanelLayout = new javax.swing.GroupLayout(workAreaJPanel);
        workAreaJPanel.setLayout(workAreaJPanelLayout);
        workAreaJPanelLayout.setHorizontalGroup(
            workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaJPanelLayout.createSequentialGroup()
                .addGroup(workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(workAreaJPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(workAreaJPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, workAreaJPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectedEnterpriseText))
                            .addComponent(manageAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageOrganizationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        workAreaJPanelLayout.setVerticalGroup(
            workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workAreaJPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(workAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(selectedEnterpriseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(manageOrganizationBtn)
                .addGap(49, 49, 49)
                .addComponent(manageAdminBtn)
                .addGap(52, 52, 52)
                .addComponent(viewReportBtn)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(workAreaJPanel);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationBtnActionPerformed
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationBtnActionPerformed

    private void manageAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAdminBtnActionPerformed
        // TODO add your handling code here:
        ManageOrganizationAdminJPanel manageOrganizationAdminJPanel = new ManageOrganizationAdminJPanel(userProcessContainer, organization);
        userProcessContainer.add("manageOrganizationAdminJPanel", manageOrganizationAdminJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageAdminBtnActionPerformed

    private void viewReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReportBtnActionPerformed
        // TODO add your handling code here:
        EnterpriseAdminViewReportJPanel enterpriseAdminViewReportJPanel = new EnterpriseAdminViewReportJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("enterpriseAdminViewReportJPanel", enterpriseAdminViewReportJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewReportBtnActionPerformed

    private void enterpriseJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_enterpriseJTreeValueChanged
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) enterpriseJTree.getLastSelectedPathComponent();
        manageAdminBtn.setEnabled(false);
        if (selectedNode != null) {
            if (selectedNode.getUserObject() instanceof Organization) {
                manageAdminBtn.setEnabled(true);
                organization = (Organization) selectedNode.getUserObject();
            }
        }
    }//GEN-LAST:event_enterpriseJTreeValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree enterpriseJTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageAdminBtn;
    private javax.swing.JButton manageOrganizationBtn;
    private javax.swing.JTextField selectedEnterpriseText;
    private javax.swing.JPanel treeJPanel;
    private javax.swing.JButton viewReportBtn;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables

    public void populateTree() {
        DefaultTreeModel model = (DefaultTreeModel) enterpriseJTree.getModel();

        ArrayList<Organization> organizationList;

        DefaultMutableTreeNode enterprises = new DefaultMutableTreeNode("Enterprises");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        root.insert(enterprises, 0);

        DefaultMutableTreeNode organizationNode;
                
        organizationList = enterprise.getOrganizationDirectory().getOrganizationList();
        for (int k = 0; k < organizationList.size(); k++) {
            organization = organizationList.get(k);
            organizationNode = new DefaultMutableTreeNode(organization);
            enterprises.insert(organizationNode, k);
        }

        model.reload();
    }
}
